name: Maven Package upon a push-ui

on: workflow_dispatch

jobs:
  build-dockers-inji-verify:
    strategy:
      matrix:
        include:
          - SERVICE_LOCATION: "verify-ui"
            SERVICE_NAME: "inji-verify-ui"
            PLATFORMS: "linux/amd64"
      fail-fast: false
    name: ${{ matrix.SERVICE_NAME }}
    uses: iiitb-pilot/kattu/.github/workflows/maven-build.yml@master
    with:
      SERVICE_LOCATION: ${{ matrix.SERVICE_LOCATION }}
      SERVICE_NAME: ${{ matrix.SERVICE_NAME }}
      PLATFORMS: ${{ matrix.PLATFORMS }}
    secrets:
      DEV_NAMESPACE_DOCKER_HUB: ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}
      ACTOR_DOCKER_HUB: ${{ secrets.ACTOR_DOCKER_HUB }}
      RELEASE_DOCKER_HUB: ${{ secrets.RELEASE_DOCKER_HUB }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  build-inji-verify-service:
    uses: iiitb-pilot/kattu/.github/workflows/maven-build.yml@master
    with:
      SERVICE_LOCATION: ./
      BUILD_ARTIFACT: inji-verify-service
      MAVEN_NON_EXEC_ARTIFACTS: "verify-service*.jar"
    secrets:
      OSSRH_USER: ${{ secrets.OSSRH_INJI_USER }}
      OSSRH_SECRET: ${{ secrets.OSSRH_INJI_SECRET }}
      OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
      GPG_SECRET: ${{ secrets.GPG_SECRET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_INJI_TEAM }}

  build-dockers:
    needs: build-inji-verify-service
    strategy:
      matrix:
        include:
          - SERVICE_LOCATION: "verify-service"
            SERVICE_NAME: "inji-verify-service"
            BUILD_ARTIFACT: "inji-verify-service"
            SQUASH_LAYERS: "7"
      fail-fast: false
    name: ${{ matrix.SERVICE_NAME }}
    uses: iiitb-pilot/kattu/.github/workflows/maven-build.yml@master
    with:
      SERVICE_LOCATION: ${{ matrix.SERVICE_LOCATION }}
      SERVICE_NAME: ${{ matrix.SERVICE_NAME }}
      BUILD_ARTIFACT: ${{ matrix.BUILD_ARTIFACT }}
      SQUASH_LAYERS: ${{ matrix.SQUASH_LAYERS }}
    secrets:
      DEV_NAMESPACE_DOCKER_HUB: ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}
      ACTOR_DOCKER_HUB: ${{ secrets.ACTOR_DOCKER_HUB }}
      RELEASE_DOCKER_HUB: ${{ secrets.RELEASE_DOCKER_HUB }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
